package jammazwan.xay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-17T11:01:24.420-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://xay.jammazwan/", name = "XayService")
@XmlSeeAlso({ObjectFactory.class})
public interface XayService {

    @WebMethod
    @RequestWrapper(localName = "getPass", targetNamespace = "http://xay.jammazwan/", className = "jammazwan.xay.GetPass")
    @ResponseWrapper(localName = "getPassResponse", targetNamespace = "http://xay.jammazwan/", className = "jammazwan.xay.GetPassResponse")
    @WebResult(name = "return", targetNamespace = "")
    public jammazwan.entity.CorporateEventPass getPass(
        @WebParam(name = "arg0", targetNamespace = "")
        jammazwan.entity.Company arg0
    );
}
