
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package jammazwan.xay;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-17T11:01:24.390-05:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "XayServiceService",
                      portName = "XayServicePort",
                      targetNamespace = "http://xay.jammazwan/",
                      wsdlLocation = "classpath:wsdl/eventPass.wsdl",
                      endpointInterface = "jammazwan.xay.XayService")
                      
public class XayServicePortImpl implements XayService {

    private static final Logger LOG = Logger.getLogger(XayServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see jammazwan.xay.XayService#getPass(jammazwan.entity.Company  arg0 )*
     */
    public jammazwan.entity.CorporateEventPass getPass(jammazwan.entity.Company arg0) { 
        LOG.info("Executing operation getPass");
        System.out.println(arg0);
        try {
            jammazwan.entity.CorporateEventPass _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
